[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
exclude = [
    "htmlcov",
] # Exclude the coverage report file from setuptools package finder

[project]
name = "PyProBE"
version = "0.1.3"
requires-python = ">=3.11"
dependencies = [
    "numpy", # for numerical operations
    "polars", # for dataframes
    "fastexcel", # for reading Excel files 
    "plotly", # for plotting
    "scikit-learn", # for statistical analysis
    "distinctipy", # for color palettes
    "streamlit", # for dashboard GUI
    "PyYAML", # for reading YAML files
    "ordered-set",
    "pydantic", # for data valiation
    "kaleido", # for displaying plotly figures as images
    "IPython", # for example notebooks
    "pybamm" # for battery modelling and experiment class
]

[project.optional-dependencies]
dev = [
    # linters and formatters
    "black",
    "flake8",
    "flake8-docstrings",
    "isort",
    "mypy",
    "pip-tools",
    "pre-commit",
    # pytest
    "pytest",
    "pytest-cov", # coverage
    "pytest-mypy", # type checking
    "pytest-mock", # mock objects
    "pytest-benchmark", # benchmarking
    # documentation
    "sphinx",
    "sphinx-tabs",
    "types-PyYAML",
    "sphinxcontrib-bibtex", # for references
    "sphinx-design",
    "pydata-sphinx-theme", # for theme
    "nbsphinx", # integrate notebooks in docs
    "xlsxwriter", # write to Excel from polars
]

[tool.mypy]
disallow_any_explicit = false
disallow_any_generics = true
warn_unreachable = true
disallow_untyped_defs = true
ignore_missing_imports = true
exclude = [".venv/", "docs/"]

[[tool.mypy.overrides]]
module = "tests.*"
disallow_untyped_defs = false
warn_unused_ignores = false

[[tool.mypy.overrides]]
module = "polars"
follow_imports = "skip"

[tool.isort]
profile = "black"

[tool.pytest.ini_options]
addopts = "-v --mypy -p no:warnings --cov=pyprobe --cov-report=html --doctest-modules --ignore=docs/ --ignore=pyprobe/"

[tool.coverage.report]
exclude_also = [
    "@overload"
]
