name: "Tests"
on:
  pull_request:
    branches:
      - main
    paths:
      - pyprobe/**
      - tests/**
      - docs/source/examples/*ipynb
      - pyproject.toml
      - .github/workflows/ci.yml
      - uv.lock
  push:
    branches:
      - main
    paths:
      - pyprobe/**
      - tests/**
      - pyproject.toml
      - .github/workflows/ci.yml
      - uv.lock
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          # Install a specific version of uv.
          version: "0.6.3"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"
      
      - name: Install the project
        run: | # install the project with pybamm for the import pybamm solution test
          uv venv --seed
          uv sync --all-extras --frozen
          source .venv/bin/activate
          uv pip install pybamm

      - name: Run tests
        run: uv run pytest --cov-report=xml -n auto

      - name: Test notebooks
        if: github.event_name == 'pull_request'
        run: |
          shopt -s extglob
          uv run pytest --nbmake -n auto docs/source/examples/!(comparing-pyprobe-performance).ipynb

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}