name: "Update contributors"
on:
  push:
    branches:
      - main
jobs:
  contrib-readme-job:
    runs-on: ubuntu-latest
    steps:
      - uses: akhilmhdh/contributors-readme-action@v2.3.10
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
